### ISSUE TITLE
SDK updated to use @smithy types and protocol http causing type errors when using mock clients

### ISSUE THREAD

**Issue by stitch-rich** [m-radzikowski/aws-sdk-client-mock#162]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Following this change to the AWS SDK https://github.com/aws/aws-sdk-js-v3/pull/4722 the mock clients throw a number of TS errors when ever mocks are created.

I have tried this with SNS, Secrets manager and Cognito Identity provider with the same result. 

### Reproduction

```
import { mockClient } from 'aws-sdk-client-mock';
import 'aws-sdk-client-mock-jest';
import { CognitoIdentityProviderClient } from '@aws-sdk/client-cognito-identity-provider';

const cognitoMock = mockClient(CognitoIdentityProviderClient); // This will show a type error 

```

### Environment

- Node version: 18.16.0
- Testing lib and version: Jest 29.5.0
- Typescript version: 5.04
- AWS SDK v3 Client mock version: 2.1.1
- AWS JS SDK libs and versions:
    - @aws-sdk/client-cognito-identity-provider 3.338.0
    - @aws-sdk/client-secrets-manager 3.338.0

**Comment by DDachev-Allaine** [comment]
I have the same issue.

- Node version: 18.12.0
- Testing lib and version: Jest 29.5.0
- Typescript version: 5.0.3
- AWS SDK v3 Client mock version: 2.1.1
- AWS JS SDK libs and versions:
  - @aws-sdk/client-dynamodb: 3.338.0
  - @aws-sdk/client-s3: 3.338.0

**Comment by m-radzikowski** [comment]
Hey,
I can't reproduce it. I get no errors with SDK version 3.338.0 or 3.341.0 (the latest one at the moment).

Please make extra sure that all AWS SDK libs are in the same version. You can also run `yarn why @aws-sdk/types` (or similar for npm and pnpm) and check if there is more than 1 version of this package installed.

If the problem persists, please create a repo with reproduction and I will take a look.

**Comment by DDachev-Allaine** [comment]
@m-radzikowski At whatversion is your `@aws-sdk/types`? I noticed the problem on my side occurred with versions above `3.272.0`

**Comment by m-radzikowski** [comment]
@DDachev-Allaine I've tested this with `@aws-sdk/types` v3.338.0 and v3.341.0, just like other deps.

Again, if you want me to look at this, provide a reproduction.

**Comment by gmol27** [comment]
I was getting the same errors using v3.342.0 (latest as of writing this comment), but resolved by explicitly adding `@aws-sdk/types` (matching version) to my dependencies.

**Comment by cchawn** [comment]
Was seeing a similar issue — making sure that all of our `@aws-sdk/*` dependencies were on the same version (latest `3.342.0`) resolved it for me! ✅

**Comment by ThomSMG** [comment]
I still have the problem even with pinned down `3.342.0` version of aws-sdk-v3 client libs as well as `@aws-sdk/types` fixed on `3.342.0`.

<img width="560" alt="Screenshot 2023-05-31 at 23 38 24" src="https://github.com/m-radzikowski/aws-sdk-client-mock/assets/132069614/07390798-489f-471f-9408-c67ea5a4549e">

<img width="562" alt="Screenshot 2023-05-31 at 23 40 09" src="https://github.com/m-radzikowski/aws-sdk-client-mock/assets/132069614/15aea1bc-cccc-4235-a3e1-63489bf8c1d5">
