### ISSUE TITLE
Custom Jest matchers not working with Typescript

### ISSUE THREAD

**Issue by andrewh318** [m-radzikowski/aws-sdk-client-mock#180]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

The custom Jest matchers don't seem to be properly supported with Typescript. I'm getting the following error when trying to use `toHaveReceivedCommand`. Note that I'm using `import 'aws-sdk-client-mock-jest'` as per the documentation. 

`Property 'toHaveReceivedCommand' does not exist on type 'Matchers<void, AwsStub<ServiceInputTypes, ServiceOutputTypes, S3ClientResolvedConfig>> & SnapshotMatchers<...> & Inverse<...> & PromiseMatchers<...>'`

When I `@ts-ignore` the line the matcher works fine, so it seems like a typing issue? (for the `expect` call?). Is there any additional configuration required to get the matchers set up for Typescript? 

### Reproduction

```
import { describe, it, expect, beforeEach } from '@jest/globals';
import { PutObjectAclCommand, S3Client } from '@aws-sdk/client-s3';
import { mockClient } from 'aws-sdk-client-mock';
import 'aws-sdk-client-mock-jest';

describe('example', () => {
    const s3Mock = mockClient(S3Client);

    beforeEach(() => {
        s3Mock.reset();
    });
    it('test', async () => {
        // Property 'toHaveReceivedCommand' does not exist on type 'Matchers<void, AwsStub<ServiceInputTypes, ServiceOutputTypes, S3ClientResolvedConfig>> & SnapshotMatchers<...> & Inverse<...> & PromiseMatchers<...>'`
        expect(s3Mock).toHaveReceivedCommand(PutObjectAclCommand);
    });
});
```

### Environment

- Node version:  16.14.0
- Testing lib and version:  Jest
- Typescript version: 5.0.4
- AWS SDK v3 Client mock version: 3.0.0
- AWS JS SDK libs and versions:
    -  @aws-sdk/client-s3": "3.387.0"

**Comment by mx0c** [comment]
same here :(

**Comment by Tanemahuta** [comment]
Check this out:
`
import * as matchers from 'aws-sdk-client-mock-jest';

describe("blubb", () => {
  expect.extend(matchers);
});
`

Be happy.

**Comment by mx0c** [comment]
still doesn't seem to work:
![image](https://github.com/m-radzikowski/aws-sdk-client-mock/assets/15305062/550ec307-7c89-430d-8ab2-9388d37eaf08)

**Comment by samchungy** [comment]
The import modifies the global types which are only available when you install `@types/jest`

**Comment by orien** [comment]
It would be awesome if it worked without using `@types/jest`. Jest now provides its own types via `@jest/globals`, as is used in the code block supplied with this issue.

**Comment by orien** [comment]
A work around is to redeclare the matcher functions. ie. copy those in use from https://github.com/m-radzikowski/aws-sdk-client-mock/blob/v3.0.0/packages/aws-sdk-client-mock-jest/src/jestMatchers.ts#L7-L70

```diff
  import { describe, it, expect, beforeEach } from '@jest/globals';
  import { PutObjectAclCommand, S3Client } from '@aws-sdk/client-s3';
- import { mockClient } from 'aws-sdk-client-mock';
+ import { MetadataBearer } from '@smithy/types'
+ import { AwsCommand, mockClient } from 'aws-sdk-client-mock';
  import 'aws-sdk-client-mock-jest';

+ declare module 'expect' {
+   interface Matchers<R> {
+     toHaveReceivedCommand<TCmdInput extends object, TCmdOutput extends MetadataBearer>
+       (command: new (input: TCmdInput) => AwsCommand<TCmdInput, TCmdOutput>): R;
+   }
+ }

  describe('example', () => {
      const s3Mock = mockClient(S3Client);

      beforeEach(() => {
          s3Mock.reset();
      });
      it('test', async () => {
          expect(s3Mock).toHaveReceivedCommand(PutObjectAclCommand);
      });
  });
```

**Comment by adiktofsugar** [comment]
They solved this with testing-library in definitely typed like this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65981

I fixed in a similar way by adding to `custom.d.ts`:

```
import type { AwsSdkJestMockMatchers } from 'aws-sdk-client-mock-jest/dist/types/jestMatchers';

declare module 'expect' {
    interface Matchers<R = void, T = {}> extends AwsSdkJestMockMatchers<R> {}
}
```

It would be nice if that was just in the package, though.

**Comment by m-radzikowski** [comment]
I've migrated to using `@jest/globals` types in Jest matcher definition, along with adding type definition for `expect` lib using under the hood. Now, matchers should work with both `@types/jest` and `@jest/globals` `expect()`.

Released in `v3.1.0-beta.0`. Please test it if you have a moment.

**Comment by nmussy** [comment]
Hey @m-radzikowski, thanks for attempting to fix this, but it's still not working for me, neither for `3.1.0-beta.0` nor `3.1.0-beta.1`. Let me know if I'm doing something wrong here:

```ts
import {
	DescribeDBEngineVersionsCommand,
	RDSClient,
} from "@aws-sdk/client-rds";
import { beforeEach, expect, it } from "@jest/globals";
import { mockClient } from "aws-sdk-client-mock";
import "aws-sdk-client-mock-jest";

const rdsMock = mockClient(RDSClient);

beforeEach(() => {
	rdsMock.reset();
});

it("demo", async () => {
	expect(rdsMock).toHaveReceivedCommand(DescribeDBEngineVersionsCommand);
});
```

`package.json`:
```json
  "devDependencies": {
    "@jest/globals": "^29.7.0",
    "@types/node": "^20.11.24",
    "aws-sdk-client-mock": "3.1.0-beta.1",
    "aws-sdk-client-mock-jest": "^3.0.1",
    "esbuild": "^0.20.1",
    "esbuild-jest": "^0.5.0",
    "jest": "^29.7.0",
    "typescript": "^5.3.3"
  },
  "dependencies": {
    "@aws-sdk/client-rds": "^3.525.0"
  }
```

I get the following type error:
```
Property 'toHaveReceivedCommand' does not exist on type 'Matchers<void, AwsStub<object, MetadataBearer, unknown>> & SnapshotMatchers<void, AwsStub<object, MetadataBearer, unknown>> & Inverse<JestMatchers<void, AwsStub<object, MetadataBearer, unknown>>> & PromiseMatchers<...>'.ts(2339)
```

I've also tried to `expect.extend(matchers);`, to no avail

**Comment by m-radzikowski** [comment]
@nmussy you need to update `aws-sdk-client-mock-jest` to `3.1.0-beta.1` as well. Then your code works fine for me.

**Comment by nmussy** [comment]
That was my issue, thanks 👍 
For reference, here is the corrected `package.json` dependencies:

```json
  "devDependencies": {
    "@jest/globals": "^29.7.0",
    "@types/node": "^20.11.24",
    "aws-sdk-client-mock": "3.1.0-beta.1",
    "aws-sdk-client-mock-jest": "3.1.0-beta.1",
    "esbuild": "^0.20.1",
    "esbuild-jest": "^0.5.0",
    "jest": "^29.7.0",
    "typescript": "^5.3.3"
  },
  "dependencies": {
    "@aws-sdk/client-rds": "^3.525.0"
  }
```

**Comment by adiktofsugar** [comment]
3.1.0-beta.1 in both packages worked for me too. Thanks!
