### ISSUE TITLE
Cannot find module '@aws-sdk/client-s3'

### ISSUE THREAD

**Issue by Czechh** [m-radzikowski/aws-sdk-client-mock#49]
**Checklist**

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**
On version `0.5.3` my tests were running successfully, but after the latest change I'm getting a module error for '@aws-sdk/client-s3'. This is issue started for me on `0.5.4` - I reverted back to the previous version and it's working again as expected.

I don't use `@aws-sdk/client-s3` at all in my application/test code. 
```
Error: Cannot find module '@aws-sdk/client-s3'
Require stack:
- /home/circleci/libs/node_modules/aws-sdk-client-mock/dist/cjs/libStorage.js
- /home/circleci/libs/node_modules/aws-sdk-client-mock/dist/cjs/index.js
- /home/circleci/libs/packages/lib-param-store/test/index_test.js
- /home/circleci/libs/node_modules/mocha/lib/esm-utils.js
- /home/circleci/libs/node_modules/mocha/lib/mocha.js
- /home/circleci/libs/node_modules/mocha/lib/cli/one-and-dones.js
- /home/circleci/libs/node_modules/mocha/lib/cli/options.js
- /home/circleci/libs/node_modules/mocha/lib/cli/cli.js
- /home/circleci/libs/node_modules/mocha/lib/cli/index.js
- /home/circleci/libs/node_modules/mocha/bin/_mocha
 ```

**Environment**

- Node version: Node 14.X
- Typescript version: Javascript
- AWS SDK v3 Client mock version: 0.5.4
- AWS JS SDK libs and versions:
  - "@aws-sdk/client-ssm": "3.26.0"

**Comment by m-radzikowski** [comment]
Thank you for reporting this. The `@aws-sdk/client-s3` should be an optional dependency, while in fact, the code requesting it is being always imported and causing this problem. I will try to fix this ASAP.

**Comment by m-radzikowski** [comment]
Fixed in #51 and released in v0.5.5.

**Comment by Kelvijn** [comment]
@m-radzikowski this is still an issue for me on all three versions mentioned here :/

**Comment by m-radzikowski** [comment]
@Kelvijn please provide a repo with reproduction.

**Comment by Ey-Jay** [comment]
@m-radzikowski This is still an issue for me as well. 

Node version: Node 16.X
Typescript version: 4.6.3
AWS SDK v3 Client mock version: 0.6.2
AWS JS SDK libs and versions:
"@aws-sdk/client-sts": "3.67.0"

**Comment by m-radzikowski** [comment]
@Ey-Jay please provide a repo with reproduction.
